// /config/modules.js
import {
  TrendingUp,
  Settings,
  Shield,
  CreditCard,
  Users,
  UserCheck,
  MapPin,
  UserCog,
  Heart,
  Calculator,
  Package,
  FolderKanban,
  Bell,
  FileText,
  Scale,
  Globe,
  ShieldCheck,
  HandHeart,
  Book,
  ClipboardList,
  LayoutDashboard,
  LayoutGrid,
  Calendar,
  Download,
  Edit,
  MessageSquare,
} from "lucide-react";

export const MODULES = [
  {
    id: "Dashboard Overview",
    name: "Overview",
    icon: TrendingUp,
    route: "/admin/dashboard/overview",
    category: "dashboard",
    desc: "Detailed charts and analytics",
  },
  {
    id: "Dashboard Summary",
    name: "Summary Cards",
    icon: LayoutGrid,
    route: "/admin/dashboard/summary",
    category: "dashboard",
    desc: "Key metrics and recent transactions",
  },
  {
    id: "Dashboard Calendar",
    name: "Calendar",
    icon: Calendar,
    route: "/admin/dashboard/calendar",
    category: "dashboard",
    desc: "Activity and events calendar",
  },
  {
    id: "Security & Access",
    name: "Security & Access",
    icon: Shield,
    route: "/add-admin",
    category: "administration",
    desc: "Manage system security",
  },
  {
    id: "task-management",
    name: "Task Management",
    icon: ClipboardList,
    route: "/admin/task-management",
    category: "administration",
    desc: "Monitor and track all campaign tasks",
  },
  {
    id: "TPF Management",
    name: "TPF Management",
    icon: Users,
    route: "/tpf-management",
    category: "people",
    desc: "Manage TPF content",
  },
  {
    id: "Donation Management",
    name: "Donation Management",
    icon: HandHeart,
    route: "/donation-management",
    category: "quick-access",
    desc: "Track donor details & activity",
  },
  {
    id: "Finance & Accounting",
    name: "Finance & Accounting",
    icon: Calculator,
    route: "/finance",
    category: "finance",
    desc: "Budgets and expense reporting",
  },
  {
    id: "Inventory",
    name: "Inventory",
    icon: Package,
    route: "/inventory",
    category: "quick-access",
    desc: "Asset and inventory tracking",
  },
  {
    id: "Financial Aid",
    name: "Financial Aid",
    icon: ShieldCheck,
    route: "/verify/financial",
    category: "operations",
    desc: "Verify financial aid forms",
  },
  {
    id: "KYC Verification",
    name: "KYC Verification",
    icon: Book,
    route: "/verify/kyc",
    category: "operations",
    desc: "Verify user KYC documents",
  },
  {
    id: "Photography",
    name: "Photography",
    icon: Bell,
    route: "/photography",
    category: "operations",
    desc: "Manage photography content",
  },
  {
    id: "Photo-Editing",
    name: "Photo Editing",
    icon: Edit,
    route: "/photo-editing",
    category: "operations",
    desc: "Process and edit campaign photos",
  },
  {
    id: "CMS-Admin",
    name: "CMS",
    icon: Globe,
    route: "/cms-admin",
    category: "operations",
    desc: "Manage content & pages",
  },
  {
    id: "Social-Media",
    name: "Social Media",
    icon: Bell,
    route: "/social-media",
    category: "operations",
    desc: "Manage Social-Media content",
  },
  {
    id: "Campaign Management",
    name: "Campaign Management",
    icon: Bell,
    route: "/campaigns",
    category: "operations",
    desc: "Campaign tracking and execution",
  },
  {
    id: "Document Management",
    name: "Document Management",
    icon: FileText,
    route: "/documentation-management",
    category: "documentation",
    desc: "Document storage and access",
  },
  {
    id: "Downloads",
    name: "Downloads",
    icon: Download,
    route: "/downloads",
    category: "quick-access",
    desc: "Export data to CSV/PDF",
  },
  {
    id: "Legal and Compliance",
    name: "Legal & Compliance",
    icon: Scale,
    route: "/legal",
    category: "documentation",
    desc: "Legal approvals and compliance",
  },
  {
    id: "Tickets-Queries",
    name: "Tickets & Queries",
    icon: Book,
    route: "/tickets-queries",
    category: "communication",
    desc: "Respond to the Tickets and Queries of the Users",
  },
  {
    id: 'Disbursement-Tasks',
    name: 'Disbursement Tasks',
    desc: 'Process beneficiary payments and transaction proofs',
    icon: CreditCard,
    category: 'operations',
    route: '/finance/disbursement',
  },

  {
    id: "Internal Communication",
    name: "Internal Chat",
    icon: MessageSquare,
    route: "/admin/communication",
    category: "communication",
    desc: "Admin-to-admin internal messaging system",
  },
  {
    id: "Communication Audit",
    name: "Communication Audit",
    icon: Shield,
    route: "/tpf-management/communication-audit",
    category: "communication",
    desc: "Monitor all internal admin conversations",
  },
];
